# Generated by Django 5.1.4 on 2024-12-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('image', models.ImageField(upload_to='media_image')),
                ('url', models.URLField()),
            ],
        ),
    ]
